Setup Api
CakeInTech/fullstack-backend pull request #1
Opened 2023-05-02 21:34 UTC by CakeInTech

- Create greetings table on the database.
- Generate a new greeting message on the controller and respond in json format. 
- Whitelist the local link of the front-end with rack-cors.

2023-05-19 17:57 UTC, descholar-ceo requested changes
Hi @CakeInTech 🤝 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has a frontend app that is missing the following [in the frontend repo]:
- [ ] There is no link to the backend in the readme file
- [ ] The readme file is missing a PR

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-05-19 18:02 UTC, CakeInTech commented
Hello @descholar-ceo,

I'm pretty sure I have added a link to the backend in the README file of the frontend, and the same goes for the frontend.

2023-05-19 18:04 UTC, CakeInTech commented
They are not just merged yet look here: 

![image](https://github.com/CakeInTech/fullstack-backend/assets/69153321/257562e5-3547-4b37-a5a6-1bab5f09afae)

![image](https://github.com/CakeInTech/fullstack-backend/assets/69153321/d324fbc9-c0d0-4129-9b1a-9c496a3364a6)

2023-05-19 18:04 UTC, CakeInTech commented
I just haven't merged the branches yet, so make sure to check the right branch. Thanks for the review, tho. 😄

2023-05-19 18:29 UTC, descholar-ceo requested changes
Hi @CakeInTech 🤝  

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that the frontend part is missing the follwoing:
- [ ] As per the requirement of the project, we are supposed to create a Pull Request on the frontend repository, which will help us to review your changes, would you please add a PR in the frontend repo ?

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-05-20 14:01 UTC, anagudelogu requested changes
# STATUS:  CHANGES REQUIRED  ♻️ 🚧 

Hi @CakeInTech, 
I'm Andres.


While you have done a great job working on this milestone 💻 , there are some issues that you still need to work on to go to the next project. ♻️ 

You are almost there, keep up the good work! 🚀 

<img src="https://media2.giphy.com/media/3ohhwi25ISXC7Z4tMs/giphy-downsized-medium.gif"/>

## Highlights
✅ Great use of Git flow. 💯 
✅ Your project is documented professionally. 📜 
✅ Descriptive PR title, summary and commit messages. 💬 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-20 14:01 UTC, anagudelogu commented on README.md
> +This project is [MIT](./LICENSE) licensed.
- [ ] 🚧 You did a great job documenting your project! 💯 However please make sure that you have a LICENSE and that its respective link in the README is working, you can follow these steps from [GitHub's official docs](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository) to set up a LICENSE. Microverse suggests using MIT! 🤓 🔧

2023-05-20 16:38 UTC, Ismailco approved these changes
### Hi @CakeInTech, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![cr-approve](https://user-images.githubusercontent.com/25227022/165483662-7b06c812-4cc0-40b9-a84c-4729d4cf10c3.gif)


## Highlights

✔️ No linter errors
✔️ Used Gitflow
✔️ Work documented professionally

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-20 16:42 UTC, merged